"""10 Oct 2026: the v3 (final) cut of Atuona film #9 = the v2 cut + Elena's four last edits, sent from her phone as Telegram
screenshots of the v2 music take C, each tied to its shot by playhead time + the stanza burned on screen:
  0:58 "Think I'll pay the bastards a visit"        shot 13  -> "change this shot to full video shot previously generated by luma"
                                                               = s13__luma.mp4 (her 9 Oct approved folder, md5 f6698c49), whole clip
  1:24 "Kira had to build a comfortable cage..."   shot 15  -> "should become shorter" (she typed "near the car": there is no car
                                                               shot in the film; the screenshot + stanza are the cage) -> 6.0 s
  1:38 "We manage to be liars in simple answers"   shot 22  -> Ule at the window: removed
  1:50 "Salt left white trails on his skin"        shot 25  -> "return to its initial length and become glitchy": planned 10 s,
                                                               the moving shot carries Crimson glitch bursts (compile `glitchy`)
Everything else is the v2 cut unchanged. Run from the repo root: python docs/atuona/film9_stanza_work/build_cut_v3.py
"""
import json

W = 'docs/atuona/film9_stanza_work'
cut = json.load(open(f'{W}/cut_v2_2026-10-10.json', encoding='utf-8'))
SHORTER_15 = 6.0          # 10 s -> 6 s: shorter, and her 21-word stanza still reads (v2's flat 5.0 s would not)
LUMA, LUMA_SRC, SLOW = 's13__luma.mp4', 5.04, 1.2

items, seen = [], set()
for it in cut['items']:
    sid = it['sid']; seen.add(sid)
    if sid == '22':
        continue
    it = dict(it)
    if sid == '13':
        it.update({'clip': LUMA, 'slow': SLOW, 'edit': round(LUMA_SRC * SLOW - 0.05, 2),
                   'qc': 'Elena 10 Oct: the full Luma take (approved 9 Oct) replaces the 3.5 s Kling 4k trim'})
        it.pop('trim', None)
    elif sid == '15':
        it['edit'] = SHORTER_15
    elif sid == '25':
        it['edit'] = it['planned_edit']; it['glitchy'] = True
    items.append(it)
assert {'13', '15', '22', '25'} <= seen

nums = sorted({int(i['poem'][1:]) for i in items if i.get('poem')})
cut['items'] = items
cut['poems_atuona'] = ' '.join(f'#{n:03d}' for n in nums if n >= 47)
cut['poems_litprom'] = ' '.join(f'#{n:03d}' for n in nums if n <= 46)
cut['moments'] = f'10.10.2026  ·  atuona.xyz Gallery  ·  Fragments\n{len(nums)} poems  ·  ATUONA + LITPROM'
cut['_note'] = "v3, 10 Oct 2026: v2 + Elena's four phone edits (13 Luma, 15 shorter, 22 out, 25 full + glitchy); see build_cut_v3.py"
out = f'{W}/cut_v3_2026-10-10.json'
json.dump(cut, open(out, 'w', encoding='utf-8'), indent=1, ensure_ascii=False)
shots = [i for i in items if 'clip' in i]
for i in shots:
    if i['sid'] in ('13', '15', '25'):
        print(f"  {i['sid']:4} {i['edit']:5}s  {i['clip']}{'  glitchy' if i.get('glitchy') else ''}")
print(len(items), 'items =', len(shots), 'shots +', len(items) - len(shots), 'flashes;', len(nums), 'poems ->', out)
